### PR TITLE
Enhance, shrink and test Docker container

### PR DESCRIPTION
**Pull request by dbast**
For details see the individual commit messages :)

Testing using travis-ci to distribute the CI jobs between the different CI providers.

Would be nice to see the Docker container uploaded to Docker Hub (Login in there via Github user and registering the repo should be enough). The README.md could be then updated regarding the usage.

Pinging also @belkone who provided the initial Dockerfile.

Thanks

### CODE REVIEW

**Comment by belkone** [comment]
Great idea!
Being on the subject of docker:
it would be good to add .dockerignore 
and following https://github.com/mkaczanowski/packer-builder-arm/issues/17, I will see if it possible to simplify dockerfile with registering quemu-user-static binaries.

**Comment by dbast** [comment]
@belkone Added a docker ignore file.

Looking at the referenced issues looks like the `multiarch/qemu-user-static:register` stuff can be added without introducing a docker-compose.yml/Makefile, by using the also the entrypoint.sh. That would be certainly interesting :) But maybe better subject for another PR :)

**Comment by belkone** [comment]
@dbast I just checked it and yes, it could be done in few simple steps;) 
I can create PR when @mkaczanowski accepts the current changes

**Comment by dbast** [comment]
@belkone ok.

Updated the .dockerignore file to be like the referenced one :)

**Comment by mkaczanowski** [comment]
> Would be nice to see the Docker container uploaded to Docker Hub
I'll set this up.

Thanks! <3

**Pull request merged**
