### PR TITLE
[OPTDEV-2284] Fixes for `step_partition_image.go`

### PR DESCRIPTION
**Pull request by michalfita**
The original code has bugs in MBR/DOS partitioniong, so narrow use cases fail miserably.

Additionally output handling is improved.

### CODE REVIEW

**Review by dbast — APPROVED** [review]

**Comment by dbast** [comment]
thanks!

**Comment by michalfita** [comment]
@dbast are you going to maintain this repo now?

**Comment by dbast** [comment]
I can, but have no permissions to enable more maintainers or to the rename required for the plugin.

**Comment by michalfita** [comment]
I'm not sure rename is still required in recent versions. Some people who forked shown demo without renaming. I haven't been there yet, some other stuff takes priority at work with our September release.

**Pull request merged**
