### PR TITLE
Add armv8 Raspi 4 example

### PR DESCRIPTION
**Pull request by bcomnes**
This builds on https://github.com/mkaczanowski/packer-builder-arm/pull/24 but also incorporates the discussion in https://github.com/mkaczanowski/packer-builder-arm/issues/15 regarding Armv8 quemu binaries.

### CODE REVIEW

**Comment by bcomnes** [comment]
Darn, looks like this needs more work.

**Comment by bcomnes** [comment]
Just retested this setup for Arm8 raspi3, and it works perfectly.  Just ordered a 4 and would like to get this path working too.  Doing more research on whats happening.

**Comment by mkaczanowski** [comment]
seems something is not in the path, try adding:
```
"image_chroot_env": ["PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"],
```

**Comment by bcomnes** [comment]
Looks that way but iirc this is the same error you get when you try to run the wrong architecture of Qemu.  Testing it out

**Comment by bcomnes** [comment]
Odd, switching back to the `/usr/bin/qemu-arm-static` for the Raspi 4 image worked.  But you need `qemu-aarch64-static` for the raspi3 image.

**Comment by bcomnes** [comment]
Also just to note, I tried `image_chroot_env` and it didn't seem to work.

**Comment by bcomnes** [comment]
Yeah I guess the raspi4 img arch arm is shipping is still arm7.  Bummer.  Added an arm8 example for the raspi3.  Please let me know if you want any tweaks made.

**Pull request merged**
