### PR TITLE
Update to packer plugin sdk and update packer to 1.7.2

### PR DESCRIPTION
**Pull request by dbast**
This is a rebase of https://github.com/mkaczanowski/packer-builder-arm/pull/71 with the packer version update in the Dockerfile and  Github workflows on top.

closes https://github.com/mkaczanowski/packer-builder-arm/pull/71

### CODE REVIEW

**Comment by dbast** [comment]
closes https://github.com/mkaczanowski/packer-builder-arm/issues/75

**Comment by dbast** [comment]
The CI failures are unrelated and the same as currently on master... some boards should be disabled/updated/removed. 

Ready for review/merge :)

**Comment by dbast** [comment]
Did some additional updates to get all boards green.

**Comment by mkaczanowski** [comment]
<3 thanks @dbast !

**Pull request merged**
